version: '3.9'
services:
  web:
    image: traefik:latest
    networks:
      - schambeck-net
    command:
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.stack.namespace" }}.localhost`)
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  schambeck-net:
    external: true
